version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/local/Dockerfile
    container_name: simple-golang-chat-app
    working_dir: /opt/www/app
    volumes:
      - ./:/opt/www/app
    ports:
      - "8080:8080"
