services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/local/Dockerfile
    container_name: simple-golang-chat-app
    working_dir: /opt/www/app
    environment:
      APP_NAME: ${APP_NAME:-Simple Golang Chat}
      APP_PORT: ${APP_PORT:-8080}
      APP_URL: ${APP_URL:-http://localhost:8080}
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS:-http://localhost:8080}
      APP_ENV: ${APP_ENV:-development}
    volumes:
      - ./:/opt/www/app
    ports:
      - "8080:8080"
